apiVersion: v2                   # Helm chart API version (v2 for Helm 3)
name: sf-biketheft-webapi         # Name of the chart
description: A Helm chart for Swapfiets Bike Theft Service API
version: 0.1.0                    # Version of the Helm chart
appVersion: "1.0.0"               # Version of the actual application being deployed
maintainers:
  - name: Abhiram Padhi               # Maintainer information
    email: abhiraampadhi@outlook.com
