replicaCount: 2

image:
  repository: <your-container-registry>/sf-biketheft-webapi
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
