name: .NET Core API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore '**/SF.BikeTheft.*.csproj'

    - name: Build solution
      run: dotnet build '**/SF.BikeTheft.*.csproj' --configuration Release

    - name: Publish API project
      run: dotnet publish 'src/WebAPI/SF.BikeTheft.WebApi.csproj' --configuration Release --output ${{ github.workspace }}/publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}/publish
